from . import hospital_person
from . import hospital_doctor
from . import hospital_patient
from . import hospital_disease
from . import hospital_appointment
from . import hospital_contact_person
from . import hospital_diagnosis
from . import hospital_doctor_history
from . import hospital_doctor_schedule
from . import hospital_analysis
